var fileindex = ["index.html", "download.html", "about.html"];
var en_US = [
  {
    title: "This is Iris",
    heading: "Iris Shaders",
    home: "Home",
    about: "Learn More",
    download: "Download Now",
    dark: " Dark mode",
    light: "Light mode",
    subheading: "A lens into a new era of minecraft graphics",
    or: "or",
    continue: "Continue Reading",
    heading1: "Why Iris?",
    subheading1: "This is what makes iris different",
    card1: "Great mod Compatibility",
    carddesc1: "Iris is committed to ensuring mod compatibility as a first priority, and is already compatible with many of your favorite mods!",
    card2: "Modern Design",
    carddesc2: "Iris has been built from the ground up to be extensible and easy to update. Say goodbye to weeks of waiting to use shaders on the new Minecraft version!",
    card3: "Free and Open Source",
    carddesc3: "Iris is an open source mod that anyone can contribute to. This allows Iris to improve by facilitating collaboration.",
    heading2: "Features",
    subheading2: "What Iris has to offer",
    image1: "OptiFine Parity",
    imagedesc1: "Iris aims to have full support for all past and present OptiFine shaderpacks, and number of packs supported by Iris is constantly and rapidly growing!<span class='text-span-2'><br>Screenshot by Niko</span>",
    image2: "Works with Sodium",
    imagedesc2: "Iris is compatible with CaffeineMC optimization mods such as Sodium and Phosphor, enabling stunning graphics at frames comparable to or even better than vanilla.<br><span class='text-span-2'>Screenshot by Guardian</span>",
    heading3: "The Iris Advantage",
    subheading3: "New rendering techniques that put you ahead of the game",
    shadows: "Shadows",
    entities: "Entities",
    screenshottitle1: "Performance-Optimized Shadows",
    screenshotdesc1: "Iris uses a technique called Shadow Frustum Culling to decrease the overhead of one of the biggest performance hogs of a shader - the shadows. Using Iris&#x27;s shadow frustum culling, you&#x27;ll be able to reach higher frame rates without sacrificing the quality of volumetric lighting or shadows.<br><span class='text-span-2'>Screenshot by FoundationGames</span>",
    screenshottitle2: "Efficient Entity Rendering",
    screenshotdesc2: "Iris improves the way that Minecraft renders entities and block entities like chests, pigs, and item frames. This trick even works with shaders disabled, and in worlds with a lot of entities, it can boost vanilla performance by up to 60 percent. Shadow rendering sees an especially large improvement, making areas that were once unplayable with shaders into places where your FPS is surprisingly smooth!<br><span class='text-span-2'>Screenshot by kinzuu_music</span>",
    footer1: "about the Iris project",
    footerdesc1: "The Iris Project is a collaborative open-source project created by a team of passionate developers seeking to make the Minecraft shaders experience the best that it can be. Iris is developed by the community, for the community.",
    footer2: "useful links",
    curseforge: "Iris on CurseForge",
    modrinth: "Iris on Modrinth",
    github: "GitHub",
    discord: "Discord",
    patreon: "Patreon",
    copyright: "© Copyright 2021 IrisShaders. All Rights Reserved."
  },
  {
    title: "This is Iris",
    home: "Home",
    about: "Learn More",
    download: "Download Now",
    dark: " Dark mode",
    light: "Light mode",
    subheading: "A lens into a new era of minecraft graphics",
    or: "or",
    continue: "Continue Reading",
    heading1: "Why Iris?",
    subheading1: "This is what makes iris different",
    card1: "Great mod Compatibility",
    carddesc1: "Iris is committed to ensuring mod compatibility as a first priority, and is already compatible with many of your favorite mods!",
    card2: "Modern Design",
    carddesc2: "Iris has been built from the ground up to be extensible and easy to update. Say goodbye to weeks of waiting to use shaders on the new Minecraft version!",
    card3: "Free and Open Source",
    carddesc3: "Iris is an open source mod that anyone can contribute to. This allows Iris to improve by facilitating collaboration.",
    heading2: "Features",
    subheading2: "What Iris has to offer",
    image1: "OptiFine Parity",
    imagedesc1: "Iris aims to have full support for all past and present OptiFine shaderpacks, and number of packs supported by Iris is constantly and rapidly growing!<span class='text-span-2'><br>Screenshot by Niko</span>",
    image2: "Works with Sodium",
    imagedesc2: "Iris is compatible with CaffeineMC optimization mods such as Sodium and Phosphor, enabling stunning graphics at frames comparable to or even better than vanilla.<br><span class='text-span-2'>Screenshot by Guardian</span>",
    heading3: "The Iris Advantage",
    subheading3: "New rendering techniques that put you ahead of the game",
    shadows: "Shadows",
    entities: "Entities",
    screenshottitle1: "Performance-Optimized Shadows",
    screenshotdesc1: "Iris uses a technique called Shadow Frustum Culling to decrease the overhead of one of the biggest performance hogs of a shader - the shadows. Using Iris&#x27;s shadow frustum culling, you&#x27;ll be able to reach higher frame rates without sacrificing the quality of volumetric lighting or shadows.<br><span class='text-span-2'>Screenshot by FoundationGames</span>",
    screenshottitle2: "Efficient Entity Rendering",
    screenshotdesc2: "Iris improves the way that Minecraft renders entities and block entities like chests, pigs, and item frames. This trick even works with shaders disabled, and in worlds with a lot of entities, it can boost vanilla performance by up to 60 percent. Shadow rendering sees an especially large improvement, making areas that were once unplayable with shaders into places where your FPS is surprisingly smooth!<br><span class='text-span-2'>Screenshot by kinzuu_music</span>",
    footer1: "about the Iris project",
    footerdesc1: "The Iris Project is a collaborative open-source project created by a team of passionate developers seeking to make the Minecraft shaders experience the best that it can be. Iris is developed by the community, for the community.",
    footer2: "useful links",
    curseforge: "Iris on CurseForge",
    modrinth: "Iris on Modrinth",
    github: "GitHub",
    discord: "Discord",
    patreon: "Patreon",
    copyright: "© Copyright 2021 IrisShaders. All Rights Reserved."
  },
];
var lang = navigator.language.replace('-', "_");



//Loading the lang
function initLang(page) { console.log("Loaded " + lang); for (const [key, value] of Object.entries(window[lang][page])) { var el = document.querySelector(`[langfield="${key}"]`); if (el) {document.querySelectorAll(`[langfield="${key}"]`).forEach((element) => (element.innerHTML = value));}}}
